version: '3.9'

x-psql-variables: &psql-variables
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    environment: *psql-variables
    ports:
      - "5432:5432"
    networks:
      - postgres_backend_bridge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres_backend_bridge
    environment:
      <<: *psql-variables
      POSTGRES_URL: postgres

networks:
  postgres_backend_bridge:
    driver: bridge