version: '3.9'

x-psql-variables: &psql-variables
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    environment: *psql-variables
    ports:
      - "5432:5432"
    networks:
      - postgres_backend_bridge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - ${APPLICATION_PORT:-8080}:${APPLICATION_PORT:-8080}
      - "9010:9010"
      - "5005:5005"
      - "2221:2221"
      # not required if FTP_ENABLED is set to false
      - ${FTP_PASSIVE_PORT_RANGE}:${FTP_PASSIVE_PORT_RANGE}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres_backend_bridge
    environment:
      <<: *psql-variables
      POSTGRES_URL: postgres
      #
      #
      #
      _JAVA_OPTIONS: >
        -Xmx2048m
        -Xms2048m
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.rmi.port=9010
        -Dcom.sun.management.jmxremote.port=9010
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=127.0.0.1
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
      #
      #
      #
      FTP_ENABLED: ${FTP_ENABLED}
      FTP_ADMIN_USER: ${FTP_ADMIN_USER}
      FTP_ADMIN_PASSWORD: ${FTP_ADMIN_PASSWORD}
      FTP_ADMIN_HOME_DIRECTORY: ${FTP_ADMIN_HOME_DIRECTORY}
      FTP_PASSIVE_PORT_RANGE: ${FTP_PASSIVE_PORT_RANGE}
      #
      #
      #
      APPLICATION_PORT: ${APPLICATION_PORT:-8080}
    volumes:
      - ftp_upload_volume:${FTP_ADMIN_HOME_DIRECTORY:-/tmp/}

networks:
  postgres_backend_bridge:
    driver: bridge

volumes:
  ftp_upload_volume: