ktor:
  application:
    modules:
      - cansu.com.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
db:
  postgres:
    url: "localhost:5432"
    user: "kotlinpsql"
    password: "c416f847e059b973ce0473b42c8ab1d3"

