ktor:
  application:
    modules:
      - cansu.com.ApplicationKt.module
  deployment:
    port: 8080
db:
  postgres:
    url: "$POSTGRES_URL:postgres"
    user: $POSTGRES_USER
    password: $POSTGRES_PASSWORD
    database: $POSTGRES_DB
